---@meta

---@class ACastle_Large_Tower_End_03_C : ABP_OMDTrapGrid_C
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W UStaticMeshComponent
---@field ColumnTrim_CastStone_600W UStaticMeshComponent
---@field ColumnTrim_CastStone_300W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W1 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_Square_SM1 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_Square_SM2 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_Square_SM UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_Square_SM3 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_SM3 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_SM1 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_SM2 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_SM UStaticMeshComponent
---@field Crenellation_Pointed_SM3 UStaticMeshComponent
---@field Crenellation_Pointed_SM2 UStaticMeshComponent
---@field Crenellation_Pointed_SM1 UStaticMeshComponent
---@field Crenellation_Pointed_Square_SM3 UStaticMeshComponent
---@field Crenellation_Pointed_Square_SM2 UStaticMeshComponent
---@field Crenellation_Pointed_Square_SM1 UStaticMeshComponent
---@field Crenellation_Pointed_Square_SM UStaticMeshComponent
---@field Crenellation_Pointed_SM UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB1 UStaticMeshComponent
---@field Wall_Bottom_016 UOMDTrapGridBoxComponent
---@field Wall_Bottom_015 UOMDTrapGridBoxComponent
---@field Wall_Bottom_014 UOMDTrapGridBoxComponent
---@field Wall_Bottom_013 UOMDTrapGridBoxComponent
---@field Wall_Bottom_012 UOMDTrapGridBoxComponent
---@field Wall_Bottom_011 UOMDTrapGridBoxComponent
---@field Wall_Bottom_010 UOMDTrapGridBoxComponent
---@field Wall_Bottom_09 UOMDTrapGridBoxComponent
---@field Wall_Middle_08 UOMDTrapGridBoxComponent
---@field Wall_Middle_07 UOMDTrapGridBoxComponent
---@field Wall_Middle_06 UOMDTrapGridBoxComponent
---@field Wall_Middle_01 UOMDTrapGridBoxComponent
---@field Wall_Bottom_08 UOMDTrapGridBoxComponent
---@field Wall_Bottom_07 UOMDTrapGridBoxComponent
---@field Wall_Bottom_06 UOMDTrapGridBoxComponent
---@field Wall_Bottom_05 UOMDTrapGridBoxComponent
---@field Wall_Bottom_04 UOMDTrapGridBoxComponent
---@field Wall_Bottom_03 UOMDTrapGridBoxComponent
---@field Wall_Bottom_02 UOMDTrapGridBoxComponent
---@field Wall_Bottom_01 UOMDTrapGridBoxComponent
---@field Wall_Middle_04 UOMDTrapGridBoxComponent
---@field Wall_Middle_03 UOMDTrapGridBoxComponent
---@field Wall_Middle_02 UOMDTrapGridBoxComponent
---@field Wall_Middle_05 UOMDTrapGridBoxComponent
---@field trapGrid USceneComponent
---@field ColumnBlock_Bottom_1_FB UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB2 UStaticMeshComponent
---@field Tower USceneComponent
ACastle_Large_Tower_End_03_C = {}



