---@meta

---@class ACastle_Large_Tower_End_02_C : ABP_OMDTrapGrid_C
---@field Roof_Tiled_x1_Base2 UStaticMeshComponent
---@field Roof_Tiled_x1_Base3 UStaticMeshComponent
---@field Roof_Tiled_x1_Base1 UStaticMeshComponent
---@field Roof_Tiled_x1_Base UStaticMeshComponent
---@field Cren_1_Half_RB3 UStaticMeshComponent
---@field Cren_1_Half_RB2 UStaticMeshComponent
---@field Cren_1_Half_RB1 UStaticMeshComponent
---@field Cren_1_Half_RB UStaticMeshComponent
---@field Roof_Tiled_x2_Base3 UStaticMeshComponent
---@field Roof_Tiled_x2_Base2 UStaticMeshComponent
---@field Crenellation_1_RB3 UStaticMeshComponent
---@field Crenellation_1_RB2 UStaticMeshComponent
---@field Roof_Tiled_x2_Base1 UStaticMeshComponent
---@field Crenellation_1_RB1 UStaticMeshComponent
---@field Roof_Tiled_x2_Base UStaticMeshComponent
---@field Crenellation_1_RB UStaticMeshComponent
---@field Wall_Bottom_016 UOMDTrapGridBoxComponent
---@field Wall_Bottom_015 UOMDTrapGridBoxComponent
---@field Wall_Bottom_014 UOMDTrapGridBoxComponent
---@field Wall_Bottom_013 UOMDTrapGridBoxComponent
---@field Wall_Bottom_012 UOMDTrapGridBoxComponent
---@field Wall_Bottom_011 UOMDTrapGridBoxComponent
---@field Wall_Bottom_010 UOMDTrapGridBoxComponent
---@field Wall_Bottom_09 UOMDTrapGridBoxComponent
---@field Wall_Middle_08 UOMDTrapGridBoxComponent
---@field Wall_Middle_07 UOMDTrapGridBoxComponent
---@field Wall_Middle_06 UOMDTrapGridBoxComponent
---@field Wall_Middle_01 UOMDTrapGridBoxComponent
---@field Wall_Bottom_08 UOMDTrapGridBoxComponent
---@field Wall_Bottom_07 UOMDTrapGridBoxComponent
---@field Wall_Bottom_06 UOMDTrapGridBoxComponent
---@field Wall_Bottom_05 UOMDTrapGridBoxComponent
---@field Wall_Bottom_04 UOMDTrapGridBoxComponent
---@field Wall_Bottom_03 UOMDTrapGridBoxComponent
---@field Wall_Bottom_02 UOMDTrapGridBoxComponent
---@field Wall_Bottom_01 UOMDTrapGridBoxComponent
---@field Wall_Middle_04 UOMDTrapGridBoxComponent
---@field Wall_Middle_03 UOMDTrapGridBoxComponent
---@field Wall_Middle_02 UOMDTrapGridBoxComponent
---@field Wall_Middle_05 UOMDTrapGridBoxComponent
---@field trapGrid USceneComponent
---@field ColumnBlock_BottomTile_1_FB1 UStaticMeshComponent
---@field ColumnBlock_Bottom_1_FB UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB4 UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB2 UStaticMeshComponent
---@field Tower USceneComponent
ACastle_Large_Tower_End_02_C = {}



