---@meta

---@class USpellbookItemDetails_UMG_C : UOMDSpellbookItemDetails
---@field UberGraphFrame FPointerToUberGraphFrame
---@field BuyButtonPulse UWidgetAnimation
---@field RespecItemSmoke UWidgetAnimation
---@field PurchaseSpecialUpgrade UWidgetAnimation
---@field PurchaseUniqueUpgrade2 UWidgetAnimation
---@field PurchaseUniqueUpgrade1 UWidgetAnimation
---@field RespecItemAll UWidgetAnimation
---@field PurchaseLevelUpgradeSmoke UWidgetAnimation
---@field RespecItem UWidgetAnimation
---@field PurchaseLevelUpgrade UWidgetAnimation
---@field PurchaseItem UWidgetAnimation
---@field CloseActionKeyHint_UMG UCloseActionKeyHint_UMG_C
---@field CloseBtn UOMDButton
---@field Description UTextBlock
---@field Dimmer UBorder
---@field DisplayNameAndLevel UTextBlock
---@field FutureLevelUpgrade1Number UTextBlock
---@field FutureLevelUpgrade1Root UCanvasPanel
---@field FutureLevelUpgrade2Number UTextBlock
---@field FutureLevelUpgrade2Root UCanvasPanel
---@field ItemImage UImage
---@field LevelIcon UImage
---@field LevelUpgradeBackground UImage
---@field LevelUpgradeDescription UTextBlock
---@field LevelUpgradePurchaseBtn UOMDButton
---@field LevelUpgradeSkullCost UTextBlock
---@field LevelUpgradeSkullRoot UBorder
---@field LockedItemHelpText UTextBlock
---@field LockedItemRoot UVerticalBox
---@field LockIcon UImage
---@field MiniquestDescription UTextBlock
---@field MiniquestHelpText UTextBlock
---@field MiniquestProgress UProgressBar
---@field MiniquestRoot UCanvasPanel
---@field MiniquestValue UTextBlock
---@field NextLevelUpgradeNumber UTextBlock
---@field NextLevelUpgradeRoot UCanvasPanel
---@field NoLevelUpgradeDescription_Text UTextBlock
---@field NoLevelUpgradeDescriptionRoot UVerticalBox
---@field NoLevelUpgradeRoot UCanvasPanel
---@field NoUpgradeIcon UImage
---@field OMDActionKeyHint_79 UOMDActionKeyHint
---@field OMDActionKeyHint_284 UOMDActionKeyHint
---@field PlacementType UTextBlock
---@field PlayerSkullsDisplay_UMG_292 UPlayerSkullsDisplay_UMG_C
---@field PurchaseBtn UOMDButton
---@field PurchaseBtnContent UBorder
---@field RespecBtn UOMDButton
---@field SafeZone_0 USafeZone
---@field SizeBox_1 USizeBox
---@field SizeBox_2 USizeBox
---@field SkullCost UTextBlock
---@field SmokePoofBlue1 UImage
---@field SmokePoofBlue2 UImage
---@field SmokePoofPurple1 UImage
---@field SmokePoofPurple2 UImage
---@field SmokePoofPurple3 UImage
---@field SmokePoofPurple4 UImage
---@field SmokePoofYellow1 UImage
---@field SmokePoofYellow2 UImage
---@field SmokeSwirlBlue UImage
---@field SmokeSwirlPurple1 UImage
---@field SmokeSwirlPurple2 UImage
---@field SmokeSwirlYellow UImage
---@field SpecialUpgradeWidget USpellbookItemUpgrade_UMG_C
---@field UniqueUpgrade1 USpellbookItemUpgrade_UMG_C
---@field UniqueUpgrade2 USpellbookItemUpgrade_UMG_C
---@field UpgradedIcon UImage
---@field UpgradesRoot UCanvasPanel
---@field GameInstance UBP_OMDGameInstance_C
---@field OnCloseClicked FSpellbookItemDetails_UMG_COnCloseClicked
---@field InsufficientSkullsColor FLinearColor
---@field UnableToPurchaseColor FLinearColor
USpellbookItemDetails_UMG_C = {}

function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_13() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_12() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_11() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_10() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_9() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_8() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_7() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_6() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_5() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_4() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_3() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_2() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_1() end
function USpellbookItemDetails_UMG_C:SequenceEvent__ENTRYPOINTSpellbookItemDetails_UMG_0() end
---@param Return_Value FText
function USpellbookItemDetails_UMG_C:GetUnlockHintText(Return_Value) end
function USpellbookItemDetails_UMG_C:UpdateDisplayNameAndLevel() end
function USpellbookItemDetails_UMG_C:UpdateLevelUpgradeData() end
function USpellbookItemDetails_UMG_C:UpdateLevelUpgradeVisibility() end
---@return ESlateVisibility
function USpellbookItemDetails_UMG_C:GetGamePadButtonHintVisibility() end
---@param MyGeometry FGeometry
---@param InFocusEvent FFocusEvent
---@return FEventReply
function USpellbookItemDetails_UMG_C:OnFocusReceived(MyGeometry, InFocusEvent) end
---@param Loaded UObject
function USpellbookItemDetails_UMG_C:OnLoaded_C9E53C6A43E570E46DF46E9C3FF121E7(Loaded) end
function USpellbookItemDetails_UMG_C:Finished_628DF9754ECF87CB89F5AD96438CB628() end
function USpellbookItemDetails_UMG_C:Finished_0BFC228A48E40AA93A287EA8DCEEDE48() end
---@param Asset TSoftObjectPtr<UObject>
function USpellbookItemDetails_UMG_C:LoadItemImage(Asset) end
function USpellbookItemDetails_UMG_C:BndEvt__CloseBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BndEvt__PurchaseBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BndEvt__LevelUpgradePurchaseBtn_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature() end
---@param Item FOMDItemProto
function USpellbookItemDetails_UMG_C:BP_CurrentItemChanged(Item) end
function USpellbookItemDetails_UMG_C:UpdateLevelUpgradeDisplay() end
function USpellbookItemDetails_UMG_C:BndEvt__SellAllUpgradesBtn_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BP_ItemUpgradesSold() end
function USpellbookItemDetails_UMG_C:Construct() end
---@param upgrade FOMDSoftProtoPtr
function USpellbookItemDetails_UMG_C:BP_ItemUpgradeUnequipped(upgrade) end
function USpellbookItemDetails_UMG_C:RefreshOtherUpgrades() end
---@param upgrade FOMDSoftProtoPtr
function USpellbookItemDetails_UMG_C:BP_ItemUpgradePurchased(upgrade) end
---@param Index int32
function USpellbookItemDetails_UMG_C:RefreshUniqueUpgrade(Index) end
function USpellbookItemDetails_UMG_C:RefreshAllUniqueUpgrades() end
function USpellbookItemDetails_UMG_C:UpdateAllUpgrades() end
function USpellbookItemDetails_UMG_C:RefreshSpecialUpgrade() end
---@param upgrade FOMDSoftProtoPtr
function USpellbookItemDetails_UMG_C:BP_ItemUpgradeEquipped(upgrade) end
function USpellbookItemDetails_UMG_C:BndEvt__UniqueUpgrade1_K2Node_ComponentBoundEvent_4_OnPurchased__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BndEvt__UniqueUpgrade2_K2Node_ComponentBoundEvent_5_OnPurchased__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BndEvt__SpecialUpgradeWidget_K2Node_ComponentBoundEvent_6_OnPurchased__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BndEvt__CloseBtn_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature() end
function USpellbookItemDetails_UMG_C:BndEvt__CloseBtn_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature() end
---@param EntryPoint int32
function USpellbookItemDetails_UMG_C:ExecuteUbergraph_SpellbookItemDetails_UMG(EntryPoint) end
function USpellbookItemDetails_UMG_C:OnCloseClicked__DelegateSignature() end


