---@meta

---@class UUBP_Postgame_C : UUserWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ANIM_RandomModeSelectedReveal UWidgetAnimation
---@field RandomModeOnLastChoiceSelected UWidgetAnimation
---@field PerfectVictorySlam UWidgetAnimation
---@field ANIM_ShowStatsHint UWidgetAnimation
---@field ANIM_ShowSpellbook UWidgetAnimation
---@field RewardsToSpellbook UWidgetAnimation
---@field ANIM_ShowSkullGlow5 UWidgetAnimation
---@field ANIM_ShowSkullGlow4 UWidgetAnimation
---@field ANIM_ShowSkullGlow3 UWidgetAnimation
---@field ANIM_ShowSkullGlow2 UWidgetAnimation
---@field ANIM_ShowSkullGlow1 UWidgetAnimation
---@field ANIM_WarMageBonusSkulls UWidgetAnimation
---@field ANIM_ApprenticeBonusSkulls UWidgetAnimation
---@field ANIM_BonusCollect5 UWidgetAnimation
---@field ANIM_BonusCollect4 UWidgetAnimation
---@field ANIM_BonusCollect3 UWidgetAnimation
---@field ANIM_BonusCollect2 UWidgetAnimation
---@field ANIM_BonusCollect1 UWidgetAnimation
---@field Banner_Looper UWidgetAnimation
---@field ANIM_HintSpellbook UWidgetAnimation
---@field ANIM_Defeat_Slam UWidgetAnimation
---@field ANIM_BonusSkulls UWidgetAnimation
---@field ANIM_NewHighScore UWidgetAnimation
---@field ANIM_SkullToPile5 UWidgetAnimation
---@field ANIM_SkullToPile4 UWidgetAnimation
---@field ANIM_SkullToPile3 UWidgetAnimation
---@field ANIM_SkullToPile2 UWidgetAnimation
---@field ANIM_SkullToPile1 UWidgetAnimation
---@field ANIM_TrapsReceived UWidgetAnimation
---@field ANIM_SkullCount_Across5 UWidgetAnimation
---@field ANIM_SkullCount_Across4 UWidgetAnimation
---@field ANIM_SkullCount_Across3 UWidgetAnimation
---@field ANIM_SkullCount_Across2 UWidgetAnimation
---@field ANIM_SkullCount_Across1 UWidgetAnimation
---@field ANIM_Victory_Slam UWidgetAnimation
---@field ApprenticeBonusSkulls UTextBlock
---@field ApprenticeSkullsContainer UHorizontalBox
---@field BigPitch UImage
---@field BigPitchBonus UImage
---@field BigPitchBonus_1 UImage
---@field BigPitchBonus_2 UImage
---@field BigPitchBonus_3 UImage
---@field BigPitchBonus_4 UImage
---@field BlueprintPNG UImage
---@field BonusMagicFlame UImage
---@field BonusMagicShockwave_1 UImage
---@field BonusSkelly UImage
---@field BonusSkullsText UTextBlock
---@field BuffChoice_0 UUBP_Postgame_RandomModeBuffChoice_C
---@field BuffChoice_1 UUBP_Postgame_RandomModeBuffChoice_C
---@field BuffChoice_2 UUBP_Postgame_RandomModeBuffChoice_C
---@field BuffChoice_3 UUBP_Postgame_RandomModeBuffChoice_C
---@field CampaignBtn UOMDButton
---@field CampaignText UTextBlock
---@field Choices UVerticalBox
---@field ClientWaitingForHostToSelectBuffText UTextBlock
---@field ContinueBtn UOMDButton
---@field ContinueText UTextBlock
---@field GrantedItemsBox UVerticalBox
---@field Image_210 UImage
---@field LeaderboardsBtn UOMDButton
---@field LeaderboardsText UTextBlock
---@field LevelName UTextBlock
---@field OMDActionKeyHint_314 UOMDActionKeyHint
---@field PerfectFlame UImage
---@field PerfectShockwave UImage
---@field PinkSwirlSmoke UImage
---@field RandomModeBuffChoiceContainer UHorizontalBox
---@field RetainerBox_0 URetainerBox
---@field RetainerBox_1 URetainerBox
---@field RetryBtn UOMDButton
---@field RetryOnApprentice UTextBlock
---@field RetryOnApprenticeBtn UOMDButton
---@field RetryText UTextBlock
---@field SafeZone_0 USafeZone
---@field ScoreValue UTextBlock
---@field Shockwave UImage
---@field Shockwave_1 UImage
---@field Shockwave_2 UImage
---@field Shockwave_3 UImage
---@field SkullPop UImage
---@field SkullReward1 UImage
---@field SkullReward2 UImage
---@field SkullReward3 UImage
---@field SkullReward4 UImage
---@field SkullReward5 UImage
---@field SkullRewardGlow1 UImage
---@field SkullRewardGlow2 UImage
---@field SkullRewardGlow3 UImage
---@field SkullRewardGlow4 UImage
---@field SkullRewardGlow5 UImage
---@field SkullsBox UHorizontalBox
---@field SkullsBox_Glow UHorizontalBox
---@field SkullsSlam UHorizontalBox
---@field Slammo UImage
---@field Slammo_1 UImage
---@field SpellbookBtn UOMDButton
---@field SpellbookContainer UCanvasPanel
---@field SpellbookGlow UImage
---@field SpellbookHintContainer UCanvasPanel
---@field SpellbookPitch UImage
---@field StatsBtn UOMDButton
---@field StatsText UTextBlock
---@field TotalSkullsText UTextBlock
---@field UBP_Postgame_RandomModeBuffChoice_Chosen_0 UUBP_Postgame_RandomModeBuffChoice_Chosen_C
---@field UBP_Postgame_RandomModeBuffChoice_Chosen_1 UUBP_Postgame_RandomModeBuffChoice_Chosen_C
---@field UpgradeBtn UOMDButton
---@field UpgradeText UTextBlock
---@field Victory UTextBlock
---@field VoidSkullBonus UImage
---@field VoidSkullBonus_1 UImage
---@field VoidSkullBonus_2 UImage
---@field VoidSkullBonus_3 UImage
---@field VoidSkullBonus_4 UImage
---@field WarMageBonusSkulls UTextBlock
---@field WarMageSkullsContainer UHorizontalBox
---@field OMDGameInstance UBP_OMDGameInstance_C
---@field bDidWin boolean
---@field SkullRewardActiveColor FLinearColor
---@field SkullRewardInactiveColor FLinearColor
---@field CurrentSkullTally int32
---@field DidGrantItem boolean
---@field CurrentBonusSkullTally int32
---@field MusicPostgame UAudioComponent
---@field NewVar_0 UUMGSequencePlayer
---@field RandomModeCurrentRewardIndex int32
---@field LastCreatedBuffWidget UUBP_Postgame_RandomModeBuffChoice_C
---@field BuffChoices TArray<FOMDSoftProtoPtr>
UUBP_Postgame_C = {}

---@param SelectedProto FOMDSoftProtoPtr
function UUBP_Postgame_C:ClientSelectBuff(SelectedProto) end
---@return ESlateVisibility
function UUBP_Postgame_C:Get_LeaderboardsBtn_Visibility_0() end
---@return ESlateVisibility
function UUBP_Postgame_C:Get_ContinueBtn_Visibility_0() end
---@param Slot int32
function UUBP_Postgame_C:GetParSkullSlot(Slot) end
function UUBP_Postgame_C:UpdateStatsHintVisibility() end
---@return ESlateVisibility
function UUBP_Postgame_C:GetSpellbookButtonHintVisibility() end
---@param Return_Value boolean
function UUBP_Postgame_C:ShowSpellbookHint(Return_Value) end
---@param Return_Value UWidget
function UUBP_Postgame_C:GetDefaultFocusWidget(Return_Value) end
---@param Enabled boolean
UUBP_Postgame_C['Set Buttons Enabled'] = function(Enabled) end
---@param Items TArray<FOMDSoftProtoPtr>
function UUBP_Postgame_C:GetMissionUnlocks(Items) end
function UUBP_Postgame_C:UpdateSpellbookVisibility() end
---@param HasUpgrade boolean
function UUBP_Postgame_C:HasPurchasedAnyUpgrade(HasUpgrade) end
---@param Skulls_Earned int32
function UUBP_Postgame_C:GetPreviousSkullsEarned(Skulls_Earned) end
function UUBP_Postgame_C:InitializeUnearnedSkulls() end
---@param Index int32
function UUBP_Postgame_C:PlaySkullToPile(Index) end
---@param Index int32
function UUBP_Postgame_C:PlaySkullCount(Index) end
---@param MyGeometry FGeometry
---@param InFocusEvent FFocusEvent
---@return FEventReply
function UUBP_Postgame_C:OnFocusReceived(MyGeometry, InFocusEvent) end
---@param Any_Unlocks boolean
function UUBP_Postgame_C:DisplayMissionGrants(Any_Unlocks) end
---@return FText
function UUBP_Postgame_C:Get_ScoreValue_Text_0() end
---@return FText
function UUBP_Postgame_C:Get_VictoryDefeat_Text_0() end
---@param ModalWidget UOMDModalWidget
function UUBP_Postgame_C:OnClosed_5DFF8D924B158B3AD8E9A5ABCC6D7A71(ModalWidget) end
---@param MessageBox UOMDMessageBox
function UUBP_Postgame_C:OnNo_4D2FC0A54546956FF05DA189F0179510(MessageBox) end
---@param MessageBox UOMDMessageBox
function UUBP_Postgame_C:OnYes_4D2FC0A54546956FF05DA189F0179510(MessageBox) end
---@param MessageBox UOMDMessageBox
function UUBP_Postgame_C:OnCancel_4D2FC0A54546956FF05DA189F0179510(MessageBox) end
---@param MessageBox UOMDMessageBox
function UUBP_Postgame_C:OnOK_4D2FC0A54546956FF05DA189F0179510(MessageBox) end
---@param ModalWidget UOMDModalWidget
function UUBP_Postgame_C:OnClosed_5794A6834941E0984E1434AE9F6CFDB9(ModalWidget) end
---@param Loaded UObject
function UUBP_Postgame_C:OnLoaded_CF00620846AF92E437486C9C1933F18C(Loaded) end
---@param ModalWidget UOMDModalWidget
function UUBP_Postgame_C:OnClosed_2A085D8C47B9174DC97CF6AC4006F065(ModalWidget) end
function UUBP_Postgame_C:Construct() end
function UUBP_Postgame_C:BndEvt__CampaignBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__SpellbookBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__StatsBtn_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__RetryBtn_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__ContinueBtn_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__CampaignBtn_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__StatsBtn_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__RetryBtn_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__ContinueBtn_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__UpgradeBtn_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__UpgradeBtn_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__UpgradeBtn_K2Node_ComponentBoundEvent_11_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__ContinueBtn_K2Node_ComponentBoundEvent_12_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__StatsBtn_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__CampaignBtn_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__RetryBtn_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__RetryOnApprenticeBtn_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__RetryOnApprenticeBtn_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__RetryOnApprenticeBtn_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature() end
UUBP_Postgame_C['[SOUND] Stop Bonus Skull Zap'] = function() end
UUBP_Postgame_C['[SOUND] Stop Bonus Skulls Appear'] = function() end
UUBP_Postgame_C['[SOUND] Stop Bonus Skull Zap to Score'] = function() end
UUBP_Postgame_C['[SOUND] Stop Item Acquisition Appear'] = function() end
UUBP_Postgame_C['[SOUND] Stop Skull Zap'] = function() end
UUBP_Postgame_C['[SOUND] Stop Postgame Sounds'] = function() end
function UUBP_Postgame_C:BndEvt__LeaderboardsBtn_K2Node_ComponentBoundEvent_19_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__LeaderboardsBtn_K2Node_ComponentBoundEvent_20_OnButtonHoverEvent__DelegateSignature() end
function UUBP_Postgame_C:BndEvt__LeaderboardsBtn_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature() end
---@param SelectedProto FOMDSoftProtoPtr
---@param ChoiceObject UUBP_Postgame_RandomModeBuffChoice_C
function UUBP_Postgame_C:OnRandomModeChoiceSelected(SelectedProto, ChoiceObject) end
function UUBP_Postgame_C:RandomMode_DisableBuffChoices() end
function UUBP_Postgame_C:PreloadRewardIcons() end
function UUBP_Postgame_C:OnCampaignBtnClicked() end
---@param GameState AOMDGameState
function UUBP_Postgame_C:OnBuffSelected(GameState) end
---@param EntryPoint int32
function UUBP_Postgame_C:ExecuteUbergraph_UBP_Postgame(EntryPoint) end


